# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    target-branch: main
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    target-branch: main
    ignore:
      - dependency-name: '@kolibri*'
  - package-ecosystem: npm
    directory: '/packages/core/'
    schedule:
      interval: weekly
    target-branch: main
    ignore:
      - dependency-name: '@kolibri*'
  - package-ecosystem: npm
    directory: '/packages/components/'
    schedule:
      interval: weekly
    target-branch: main
    ignore:
      - dependency-name: '@kolibri*'
  - package-ecosystem: npm
    directory: '/packages/schema/'
    schedule:
      interval: weekly
    target-branch: main
    ignore:
      - dependency-name: '@kolibri*'
  - package-ecosystem: npm
    directory: '/packages/themes/'
    schedule:
      interval: weekly
    target-branch: main
    ignore:
      - dependency-name: '@kolibri*'
  - package-ecosystem: npm
    directory: '/packages/adapters/angular/'
    schedule:
      interval: weekly
    target-branch: main
    ignore:
      - dependency-name: '@kolibri*'
  - package-ecosystem: npm
    directory: '/packages/adapters/preact/'
    schedule:
      interval: weekly
    target-branch: main
    ignore:
      - dependency-name: '@kolibri*'
  - package-ecosystem: npm
    directory: '/packages/adapters/react/'
    schedule:
      interval: weekly
    target-branch: main
    ignore:
      - dependency-name: '@kolibri*'
  - package-ecosystem: npm
    directory: '/packages/adapters/solid/'
    schedule:
      interval: weekly
    target-branch: main
    ignore:
      - dependency-name: '@kolibri*'
  - package-ecosystem: npm
    directory: '/packages/adapters/svelte/'
    schedule:
      interval: weekly
    target-branch: main
    ignore:
      - dependency-name: '@kolibri*'
  - package-ecosystem: npm
    directory: '/packages/adapters/vue/'
    schedule:
      interval: weekly
    target-branch: main
    ignore:
      - dependency-name: '@kolibri*'
