packages:
  - 'packages/components'
  - 'packages/components/adapters/angular'
  - 'packages/components/adapters/preact'
  - 'packages/components/adapters/react'
  - 'packages/components/adapters/solid'
  - 'packages/components/adapters/vue'
  - 'packages/schema'
