/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { InputControl } from "@leanup/form";
import { InputTypeOnDefault } from "@kolibri/lib/dist/types/types/input/types";
export namespace Components {
    interface LeanInputAdapter {
        /**
          * Gibt das Input-Control des Eingabefeldes an.
         */
        "_control": InputControl;
        /**
          * Gibt an wie viele Millisekunden das Rerendering beim Änderungen des Wertes verzögert werden soll.
         */
        "_debounce"?: number;
        /**
          * Gibt die EventCallback-Funktionen für das Input-Event an.
         */
        "_on"?: InputTypeOnDefault;
    }
}
declare global {
    interface HTMLLeanInputAdapterElement extends Components.LeanInputAdapter, HTMLStencilElement {
    }
    var HTMLLeanInputAdapterElement: {
        prototype: HTMLLeanInputAdapterElement;
        new (): HTMLLeanInputAdapterElement;
    };
    interface HTMLElementTagNameMap {
        "lean-input-adapter": HTMLLeanInputAdapterElement;
    }
}
declare namespace LocalJSX {
    interface LeanInputAdapter {
        /**
          * Gibt das Input-Control des Eingabefeldes an.
         */
        "_control": InputControl;
        /**
          * Gibt an wie viele Millisekunden das Rerendering beim Änderungen des Wertes verzögert werden soll.
         */
        "_debounce"?: number;
        /**
          * Gibt die EventCallback-Funktionen für das Input-Event an.
         */
        "_on"?: InputTypeOnDefault;
    }
    interface IntrinsicElements {
        "lean-input-adapter": LeanInputAdapter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lean-input-adapter": LocalJSX.LeanInputAdapter & JSXBase.HTMLAttributes<HTMLLeanInputAdapterElement>;
        }
    }
}
