# This is a basic workflow to help you get started with Actions

name: CI

env:
  access: restricted
  registry: https://npm.pkg.github.com
  scope: leanupjs
  token: ${{ secrets.GITHUB_TOKEN }}

on:
  # pull_request:
  #   branches:
  #     - main
  push:
    # branches-ignore:
    #   - main
  # release:
  #   types:
  #     - released
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Replace scope in all package.json's
        run: |
          find packages -name "*.js" -type f -exec sed -i -e "s/@leanup/kolibri-@${{env.scope}}/g" {} +
          find packages -name "*.json" -type f -exec sed -i -e "s/@leanup/kolibri-@${{env.scope}}/g" {} +
          find packages -name "*.md" -type f -exec sed -i -e "s/@leanup/kolibri-@${{env.scope}}/g" {} +
          find packages -name "*.mdx" -type f -exec sed -i -e "s/@leanup/kolibri-@${{env.scope}}/g" {} +
          find packages -name "*.ts" -type f -exec sed -i -e "s/@leanup/kolibri-@${{env.scope}}/g" {} +
          find packages -name "*.tsx" -type f -exec sed -i -e "s/@leanup/kolibri-@${{env.scope}}/g" {} +
          git diff
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 16
          registry-url: '${{env.registry}}'
          scope: '@${{env.scope}}'
      - name: Install
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
        run: |
          npx lerna exec --stream -- pnpm i --frozen-lockfile=false
          pnpm i
      - name: Format
        run: |
          npx lerna run format
      - name: Lint
        run: |
          npx lerna run lint
      - name: Test
        run: |
          npx lerna run test
      # - name: 'Pack'
      #   run: |
      #     npx lerna exec --stream -- pnpm pack
