# This is a basic workflow to help you get started with Actions

name: Publish

env:
  access: restricted
  registry: https://npm.pkg.github.com
  scope: leanupjs
  token: ${{ secrets.GITHUB_TOKEN }}

on:
  # pull_request:
  #   branches:
  #     - main
  # push:
  #   branches:
  #     - main
  # release:
  #   types:
  #     - released
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Replace scope in all package.json's
        run: |
          find packages -name "*.js" -type f -exec sed -i -e "s/@leanup/kolibri-@${{env.scope}}/g" {} +
          find packages -name "*.json" -type f -exec sed -i -e "s/@leanup/kolibri-@${{env.scope}}/g" {} +
          find packages -name "*.md" -type f -exec sed -i -e "s/@leanup/kolibri-@${{env.scope}}/g" {} +
          find packages -name "*.mdx" -type f -exec sed -i -e "s/@leanup/kolibri-@${{env.scope}}/g" {} +
          find packages -name "*.ts" -type f -exec sed -i -e "s/@leanup/kolibri-@${{env.scope}}/g" {} +
          find packages -name "*.tsx" -type f -exec sed -i -e "s/@leanup/kolibri-@${{env.scope}}/g" {} +
          git diff
      # - uses: pnpm/action-setup@v2.2.2
      #   with:
      #     version: 7
      - uses: actions/setup-node@v3
        with:
          # cache: pnpm
          node-version: 16
          registry-url: '${{env.registry}}'
          scope: '@${{env.scope}}'
      - name: Build and publish core
        run: |
          npm i
          npm publish --access=${{env.access}} || true
        working-directory: packages/core
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Build and publish schema
        run: |
          npm i
          npm publish --access=${{env.access}} || true
        working-directory: packages/schema
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Build and publish components
        run: |
          npm i
          npm publish --access=${{env.access}} || true
        working-directory: packages/components
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Build and publish themes
        run: |
          npm i
          npm publish --access=${{env.access}} || true
        working-directory: packages/themes
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Build and publish adapter angular
        run: |
          npm i
          npm publish --access=${{env.access}} || true
        working-directory: packages/adapters/angular
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      # - name: Build and publish adapter preact
      #   run: |
      #     npm i
      #     npm publish --access=${{env.access}} || true
      #   working-directory: packages/adapters/preact
      #   env:
      #     NODE_AUTH_TOKEN: ${{env.token}}
      - name: Build and publish adapter react
        run: |
          npm i
          npm publish --access=${{env.access}} || true
        working-directory: packages/adapters/react
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      - name: Build and publish adapter solid
        run: |
          npm i
          npm publish --access=${{env.access}} || true
        working-directory: packages/adapters/solid
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
      # - name: Build and publish adapter svelte
      #   run: |
      #     npm i
      #     npm publish --access=${{env.access}} || true
      #   working-directory: packages/adapters/svelte
      #   env:
      #     NODE_AUTH_TOKEN: ${{env.token}}
      # - name: Build and publish adapter vue
      #   run: |
      #     npm i
      #     npm publish --access=${{env.access}} || true
      #   working-directory: packages/adapters/vue
      #   env:
      #     NODE_AUTH_TOKEN: ${{env.token}}
